export const ROUTES = {
  HOME: "/home",
  LOGIN: "/login",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  BOOKMARKS: "/bookmarks",
  HIGHLIGHTS: "/highlights",
  COLLECTIONS: "/collections",
  PROFILE: "/profile",
  PROFILE_DID: "/profile/:did",
  NEW: "/new",
  URL: "/url",
  COLLECTION_DETAIL: "/:handle/collection/:rkey",
  ANNOTATION_AT: "/at/:did/:rkey",
  ANNOTATION_URI: "/annotation/:uri",
  ANNOTATION_HANDLE: "/:handle/annotation/:rkey",
  HIGHLIGHT_HANDLE: "/:handle/highlight/:rkey",
  BOOKMARK_HANDLE: "/:handle/bookmark/:rkey",
  USER_URL: "/:handle/url/*",
} as const;
